### ISSUE TITLE
Undefined module "os"

### ISSUE THREAD

**Issue by awickert** [jacobzahn/CO2_Sol_Model_Real_Data#2]
```
$ python CO2_Sol_main.py 
Traceback (most recent call last):
  File "CO2_Sol_main.py", line 10, in <module>
    import CO2_Sol_globals as gl
  File "/home/awickert/Dropbox/Courses/Computational-Methods-in-Earth-Sciences/StudentProjects2017/Zahn_Jacob/CO2_Sol_Model_Real_Data/CO2_Sol_globals.py", line 16, in <module>
    fn = os.path.join(os.path.dirname(__file__), 'ncomms14845-s3-2.xlsx')
NameError: name 'os' is not defined
```

**Comment by jacobzahn** [comment]
Oops! I forgot to import os, but have corrected the error.
